# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-20 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('poster', 'POSTER'), ('logo', 'LOGO'), ('icon', 'ICON')], default='poster', max_length=15)),
                ('size', models.CharField(choices=[('1080 x 1920', '1080_X_1920'), ('1080 x 1080', '1080_X_1080')], default='1080 x 1920', max_length=15)),
                ('description', models.TextField()),
            ],
        ),
    ]
