# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('POSTER', 'poster'), ('LOGO', 'logo'), ('ICON', 'icon')], default='poster', max_length=15)),
                ('size', models.CharField(choices=[('1080_X_1920', '1080 x 1920'), ('1080_X_1080', '1080 x 1080')], default='1080 x 1920', max_length=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomProduct',
        ),
    ]
