# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-22 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_product', '0002_auto_20200421_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
