# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-22 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200418_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('1080_X_1920', '1080 x 1920'), ('1080_X_1080', '1080 x 1080')], default='1080 x 1920', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('POSTER', 'poster'), ('LOGO', 'logo'), ('ICON', 'icon')], default='poster', max_length=15),
        ),
    ]
