# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('10', '1080 x 1920'), ('20', '1080 x 1080')], default='1080 x 1920', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('100', 'poster'), ('50', 'logo'), ('20', 'icon')], default='poster', max_length=15),
        ),
    ]
