# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-07 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200430_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('2000_X_1920', '2000 x 1920'), ('1080_X_1920', '1080 x 1920'), ('720_X_720', '720 x 720'), ('720_X_400', '720 x 400'), ('400_X_400', '400 x 400'), ('200_X_200', '200 x 200'), ('100_X_100', '100 x 100')], default='1080 x 1920', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('POSTER', 'poster'), ('LOGO', 'logo'), ('ICON', 'icon')], default='poster', max_length=15),
        ),
    ]
